alias vd='vimdiff -O'
alias vh='vim ~/.zsh_history'
alias vi='vim -p'
alias vim='vim -p'
alias vp='vim $HOME/repos/zsh/prompt.sh       && source $HOME/repos/zsh/prompt.sh'
alias vz='vi ~/.zshrc; source ~/.zshrc'
